### ISSUE TITLE
学習プランの解析に使おうとしているライブラリの名称を教えてください

### ISSUE THREAD

**Issue by KazukoShikiya** [TakuKobayashi/teacherHack#1]
@TakuKobayashi さん

プレゼンの資料のほうで、コラボ学習のプラン内容を比較・選出するときの、比較用ライブラリの名前を知りたいそうです。
このissueへの返答でかまいませんので、使う予定のライブラリの正式名を記入願えますか？

**Comment by TakuKobayashi** [comment]
ライブラリ名はMeCabです。
http://taku910.github.io/mecab/

**Comment by KazukoShikiya** [comment]
Thanks!
